### Water quality data retrieved from https://insightsdata.sfwmd.gov/#/waterquality

In [63]:
import pandas as pd

In [64]:
wq_data = pd.read_csv(r'C:\Users\ianra\Downloads\sfwmd-data-202603191442.csv', comment='#', low_memory = False)
wq_data.head()

,station,project,collectDate,sampleType,programType,matrix,collectMethod,firstTriggerDate,depth,depthUnits,...,samplingPurpose,dataInvestigation,receiveDate,LIMSNumber,measureDate,method,filtrationDate,storetCode,sampleComment,resultComment
0,JUDGES_DCH,TOHONRP,2018-06-13 09:55,EB,MON,DI,G,NaN,0.0,NaN,...,BA,NaN,2018-06-20 08:41,65285001,2018-06-13 09:55,SFWMD-FSQM,NaN,78.0,"EB FOR P94124-14,15,16,17,18",NaN
1,JUDGES_DCH,TOHONRP,2018-07-06 09:15,EB,MON,DI,G,NaN,0.0,NaN,...,BA,NaN,2018-07-13 09:40,65836001,2018-07-06 09:15,SFWMD-FSQM,NaN,78.0,P94811-1 EB FOR P94813-11 TO 19; DATA ENETERED...,NaN
2,JUDGES_DCH,TOHONRP,2018-09-07 10:00,EB,MON,DI,G,NaN,NaN,NaN,...,BA,NaN,2018-09-11 11:14,66247001,2018-09-07 10:00,SFWMD-FSQM,NaN,78.0,P95420-1 is EB for P95242-12 through 19,NaN
3,LWL-1,LWL,2018-06-22 12:40,FCEB,MON,DI,G,NaN,0.0,NaN,...,BA,NaN,2018-06-22 15:27,65559010,2018-06-22 12:40,SFWMD-FSQM,NaN,78.0,NaN,NaN
4,LWL-1,LWL,2018-08-23 13:00,FCEB,MON,DI,G,NaN,0.0,NaN,...,BA,NaN,2018-08-24 09:15,66028007,2018-08-23 13:00,SFWMD-FSQM,NaN,78.0,NaN,NaN

In [65]:
print(wq_data.columns.tolist())
print(wq_data.dtypes)
print(wq_data.shape)
#list of all column names, stations, data types, dataframe shape

['station', 'project', 'collectDate', 'sampleType', 'programType', 'matrix', 'collectMethod', 'firstTriggerDate', 'depth', 'depthUnits', 'testNumber', 'parameter', 'dataType', 'value', 'remarkCode', 'flag', 'sigFigValue', 'uncertainty', 'dilution', 'mdl', 'pql', 'rdl', 'units', 'nDec', 'bdl', 'qualityCode', 'sampleID', 'upDownStream', 'discharge', 'weatherCode', 'collectionSpan', 'dcsMeters', 'totalDepth', 'upperDepth', 'lowerDepth', 'latitude', 'longitude', 'collectionAgency', 'workLab', 'source', 'owner', 'validator', 'validationLevel', 'samplingPurpose', 'dataInvestigation', 'receiveDate', 'LIMSNumber', 'measureDate', 'method', 'filtrationDate', 'storetCode', 'sampleComment', 'resultComment']
station               object
project               object
collectDate           object
sampleType            object
programType           object
matrix                object
collectMethod         object
firstTriggerDate     float64
depth                float64
depthUnits            object
testNumber             int64
parameter             object
dataType              object
value                float64
remarkCode            object
flag                  object
sigFigValue           object
uncertainty           object
dilution             float64
mdl                  float64
pql                  float64
rdl                  float64
units                 object
nDec                 float64
bdl                   object
qualityCode           object
sampleID              object
upDownStream          object
discharge              int64
weatherCode            int64
collectionSpan       float64
dcsMeters            float64
totalDepth           float64
upperDepth           float64
lowerDepth           float64
latitude             float64
longitude            float64
collectionAgency      object
workLab               object
source                object
owner                 object
validator             object
validationLevel      float64
samplingPurpose       object
dataInvestigation     object
receiveDate           object
LIMSNumber            object
measureDate           object
method                object
filtrationDate        object
storetCode           float64
sampleComment         object
resultComment         object
dtype: object
(173696, 53)

In [66]:
wq_data['collectDate'] = pd.to_datetime(wq_data['collectDate'])
wq_data = wq_data.set_index('collectDate')
wq_data.head()

,station,project,sampleType,programType,matrix,collectMethod,firstTriggerDate,depth,depthUnits,testNumber,...,samplingPurpose,dataInvestigation,receiveDate,LIMSNumber,measureDate,method,filtrationDate,storetCode,sampleComment,resultComment
collectDate,,,,,,,,,,,,,,,,,,,,,
2018-06-13 09:55:00,JUDGES_DCH,TOHONRP,EB,MON,DI,G,NaN,0.0,NaN,11,...,BA,NaN,2018-06-20 08:41,65285001,2018-06-13 09:55,SFWMD-FSQM,NaN,78.0,"EB FOR P94124-14,15,16,17,18",NaN
2018-07-06 09:15:00,JUDGES_DCH,TOHONRP,EB,MON,DI,G,NaN,0.0,NaN,11,...,BA,NaN,2018-07-13 09:40,65836001,2018-07-06 09:15,SFWMD-FSQM,NaN,78.0,P94811-1 EB FOR P94813-11 TO 19; DATA ENETERED...,NaN
2018-09-07 10:00:00,JUDGES_DCH,TOHONRP,EB,MON,DI,G,NaN,NaN,NaN,11,...,BA,NaN,2018-09-11 11:14,66247001,2018-09-07 10:00,SFWMD-FSQM,NaN,78.0,P95420-1 is EB for P95242-12 through 19,NaN
2018-06-22 12:40:00,LWL-1,LWL,FCEB,MON,DI,G,NaN,0.0,NaN,11,...,BA,NaN,2018-06-22 15:27,65559010,2018-06-22 12:40,SFWMD-FSQM,NaN,78.0,NaN,NaN
2018-08-23 13:00:00,LWL-1,LWL,FCEB,MON,DI,G,NaN,0.0,NaN,11,...,BA,NaN,2018-08-24 09:15,66028007,2018-08-23 13:00,SFWMD-FSQM,NaN,78.0,NaN,NaN

In [67]:
print(wq_data.index.min()) 
print(wq_data.index.max())

2015-01-05 07:14:00
2025-12-31 12:20:00

In [68]:
# Check which columns you actually need
print(wq_data.columns.tolist())

# Check how many unique stations you have
print(f"Unique stations: {wq_data['station'].nunique()}")
print(wq_data['station'].unique())

# Check which parameters are available
print(f"Unique parameters: {wq_data['parameter'].nunique()}")
print(wq_data['parameter'].unique())

['station', 'project', 'sampleType', 'programType', 'matrix', 'collectMethod', 'firstTriggerDate', 'depth', 'depthUnits', 'testNumber', 'parameter', 'dataType', 'value', 'remarkCode', 'flag', 'sigFigValue', 'uncertainty', 'dilution', 'mdl', 'pql', 'rdl', 'units', 'nDec', 'bdl', 'qualityCode', 'sampleID', 'upDownStream', 'discharge', 'weatherCode', 'collectionSpan', 'dcsMeters', 'totalDepth', 'upperDepth', 'lowerDepth', 'latitude', 'longitude', 'collectionAgency', 'workLab', 'source', 'owner', 'validator', 'validationLevel', 'samplingPurpose', 'dataInvestigation', 'receiveDate', 'LIMSNumber', 'measureDate', 'method', 'filtrationDate', 'storetCode', 'sampleComment', 'resultComment']
Unique stations: 805
['JUDGES_DCH' 'LWL-1' 'LWL-11' 'LWL-17' 'LWL-18' 'LWL-5' 'BB52' 'BB53'
 'BL01' 'CES02' 'CES03' 'CES04' 'CES05' 'CES06' 'CES07' 'CES08' 'CES09'
 'CES11' 'FLAB04' 'FLAB05' 'FLAB06' 'FLAB07' 'FLAB08' 'FLAB09' 'FLAB10'
 'FLAB11' 'FLAB12' 'FLAB13' 'FLAB14' 'FLAB15' 'FLAB16' 'FLAB17' 'FLAB18'
 'FLAB19' 'FLAB20' 'FLAB21' 'FLAB23' 'FLAB24' 'FLAB25' 'FLAB27' 'FLAB29'
 'FLAB30' 'FLAB31' 'FLAB33' 'FLAB34' 'FLAB35' 'FLAB36' 'FLAB37' 'FLAB38'
 'FLAB39' 'FLAB40' 'FLAB41' 'FLAB43' 'FLAB44' 'FLAB47' 'FLAB48' 'HR1'
 'IRL06' 'IRL08B' 'IRL11B' 'IRL12B' 'IRL15C' 'IRL17B' 'IRL18B' 'IRL22'
 'IRL27' 'IRL31C' 'IRL34B' 'IRL36' 'IRL36B' 'IRL39B' 'LWL-10' 'LWL-13'
 'LWL-15' 'LWL-16' 'LWL-2' 'LWL-4' 'LWL-6' 'LWL-7' 'LWL-8' 'MI01' 'MW01'
 'PR01' 'ROOK455' 'ROOK456' 'ROOK458' 'ROOK460' 'ROOK461' 'ROOK471'
 'ROOK476' 'ROOK477' 'SE 01' 'SE 02' 'SE 03' 'SE 06' 'SE 08' 'SE 08B'
 'SE 09' 'SE 11' 'SE 12' 'SE 13' 'SE06B' 'SE12B' 'SE13B' 'TTI51' 'TTI51B'
 'TTI52' 'TTI55' 'TTI57' 'TTI59' 'TTI64' 'TTI68B' 'TTI69' 'TTI70B' 'TTI71'
 'TTI72' 'TTI75' 'TTI75B' 'TTI75C' 'TTI76B' 'A03' 'B02' 'B06' 'B09'
 'BARRON' 'BC10' 'BC11' 'BC14' 'BC16' 'BC19' 'BC2' 'BC22' 'BC3' 'BC9'
 'C03' 'CLV10A' 'COCAT41' 'COCPALM' 'CORK@846' 'CORKSCRD' 'CULV10A' 'D02'
 'D03' 'E02' 'E04' 'EASTSHORE' 'ECOCORIV' 'ET05253114' 'ET06253113' 'FAKA'
 'FAKAUPOI' 'FANNY_BASS' 'FEBIN' 'FEBOUT' 'FISH_LAKE' 'GATOR_BAY'
 'GGC@858' 'GGCAT31' 'HALDCRK' 'HEND@951' 'ISTK1' 'ISTK2S' 'ISTK3W'
 'ISTK5N' 'ISTK6' 'KBARSE' 'KISSR0.0' 'KREA 101' 'KREA 102' 'KREA 91'
 'KREA 92' 'KREA 93' 'KREA 94' 'KREA 97' 'KREA 98' 'L001' 'L004' 'L005'
 'L006' 'L007' 'L008' 'LELY' 'LZ2' 'LZ25A' 'LZ30' 'LZ40' 'MBOXSOU'
 'MH16000' 'MH24000' 'MH32000' 'NB2' 'NB4' 'NCENTER' 'NES135' 'NES191'
 'N_STEWART' 'OISLAND' 'PALMOUT' 'PALMOUT1' 'PALMOUT2' 'PALMOUT3'
 'PARTIN_CNL' 'PC21' 'PC34' 'PC44' 'PC45' 'PELBAY3' 'POIN_FIRE' 'POLE3S'
 'POLESOUT' 'POLESOUT1' 'POLESOUT2' 'POLESOUT3' 'QUAIL_RDG' 'RITTAE2'
 'RUNNYMEDE' 'S351' 'S352' 'S354' 'S5A' 'S_GRANADA' 'TAMTOM' 'TIN13700'
 'TIN16100' 'WPA_CNL' '02270500' '02273198' 'ABOGGN' 'AJC1' 'BC25'
 'BERMB3' 'BL02' 'BNSHINGLE' 'BS-59' 'BWR1' 'C-1059' 'C-1064' 'C-1080'
 'C-1277' 'C-984' 'C123SR84' 'C139S1' 'C139S2' 'C139S3' 'C139S6' 'C17S44'
 'C18G92' 'C18S46' 'C23S48' 'C24S49' 'C25S50' 'C38W' 'C41H78' 'C44C1'
 'C44C2' 'C44S80' 'C51S155' 'CA217' 'CA27' 'CA315' 'CA316' 'CA317' 'CA318'
 'CA36' 'CCS3R' 'COOPERTN' 'CR92C1' 'CREEDYBR' 'DAVIS BR' 'DF02.1TW'
 'FECSR78' 'FOCQC' 'G136' 'G150' 'G151W' 'G161' 'G36LCS' 'G378B' 'G378E'
 'G388' 'G389B' 'G390A' 'G390B' 'G409' 'G538' 'G539' 'G81' 'G92_T' 'G94A'
 'G94C' 'GGW-4S' 'GLADER' 'GORDYRD' 'INDUSCAN' 'IRL08' 'KRDR02' 'KREA 28'
 'L10C3' 'L28I' 'L3BRS' 'L60E' 'L60W' 'L8.M CNL' 'LABQC' 'LOX10' 'LOX11'
 'LOX12' 'LOX13' 'LOX4' 'LOX5' 'N01' 'NSID1US' 'OKALA858' 'OKEELAB' 'P33'
 'P34' 'PC11R' 'PC17A' 'PM1' 'PM2' 'PM3' 'PM4' 'PM5' 'ROOK467' 'S10A'
 'S10C' 'S10D' 'S11A' 'S11B' 'S11C' 'S127' 'S129' 'S12A' 'S12B' 'S12C'
 'S12D' 'S131' 'S133' 'S135LOCKDS' 'S135LOCKUS' 'S135LS' 'S140' 'S142'
 'S142-D' 'S145' 'S150' 'S151' 'S152' 'S153DS' 'S154' 'S154C' 'S169'
 'S177' 'S178' 'S18C' 'S190' 'S191' 'S193CS' 'S193LS' 'S197' 'S2' 'S200'
 'S235' 'S236' 'S3' 'S308C' 'S308LDS' 'S308LUS' 'S31' 'S328' 'S331-173'
 'S332B' 'S332C' 'S332DX' 'S333' 'S333N' 'S334' 'S335' 'S335TW' 'S34'
 'S342N' 'S344' 'S352_T' 'S355A' 'S355ATW' 'S355B' 'S355BTW' 'S356'
 'S356-334' 'S357' 'S38' 'S385' 'S39' 'S390' 'S391' 'S392' 'S4' 'S488'
 'S5AE' 'S5AS' 'S5AW' 'S65' 'S650' 'S654A' 'S656A' 'S65A' 'S65C' 'S65D'
 'S65DX1' 'S65E' 'S660' 'S7' 'S700' 'S71' 'S72' 'S77' 'S77LDS' 'S77S1'
 'S78' 'S78_LCK_H' 'S79' 'S8' 'S84' 'S9' 'S9A' 'SAFARI' 'SM00.4TW' 'SRS2'
 'SWPFC3' 'TAMBR105' 'TMBR39' 'TTI70' 'U3' 'US41-25' 'USSO' 'WPB-26.1'
 'WPB-28.2' 'WWEIR' 'BF-4M' 'BF-6' 'BOYRO_EPXU' 'C-1003' 'C-1004' 'C-1055'
 'C-1058' 'C-1061' 'C-1073' 'C-1077' 'C-1078' 'C-1079' 'C-1097' 'C-1100'
 'C-1275' 'C-1276' 'C-1278' 'C-1283' 'C-1286' 'C-298' 'C-311' 'C-489'
 'C-490' 'C-528' 'C-531' 'C-532' 'C-600' 'C-684' 'C-687' 'C-688' 'C-689'
 'C-965' 'C-966' 'C-974' 'C-976' 'C-977' 'C-985' 'C-986' 'C-989' 'C-995'
 'C-996' 'CCN1R' 'CCN3' 'CCS1' 'GGW-1D' 'GGW-1S' 'GGW-4D' 'HE-517'
 'HE-529' 'HE-557' 'HIF-6' 'KW-MZL' 'L-1418' 'L-1691' 'L-1963' 'L-1968'
 'L-1974' 'L-2186' 'L-2187' 'L-2200' 'L-2313' 'L-2328' 'L-2525' 'L-2528'
 'L-2550' 'L-2643' 'L-2644' 'L-2646' 'L-2820' 'L-5641' 'L-5648' 'L-5664'
 'L-5708' 'L-5734' 'L-652' 'L-735' 'L-742' 'MF-37L' 'MF-40L' 'MF-52RL'
 'MF-52RU' 'OKF-100L' 'OKF-13' 'OKF-23' 'OKF-31' 'OSF-22' 'PBF-10R'
 'PBF-11' 'PBF-12' 'PBF-15M' 'PBF-2' 'PBF-4' 'POF-6' 'POF-8' 'RTA-005'
 'RTA-007' 'S356GW1' 'S356GW2' 'S356GW3' 'S356GW4' 'SLF-21' 'SLF-74'
 'SLF-76' 'TCRK_GW1' 'TCRK_GW2' 'CURCIE' 'CA28' 'CA29' 'CA311' 'CA32'
 'CA33' 'CA34' 'CA35' 'CA38' 'CR-00.1' 'CULV5' 'CULV5A' 'EP' 'G36LLS'
 'G389A' 'G64' 'L59E' 'L59W' 'L61E' 'LOX14' 'LOX15' 'LOX16' 'LOX3' 'LOX6'
 'LOX7' 'LOX8' 'LOX9' 'NE0' 'NE1' 'NP201' 'P35' 'P36' 'P37' 'S135' 'S153'
 'S155A' 'S271' 'S77BR' 'S77_T' 'SWPFC1' 'SWPFC2' 'TAMICNLW' 'TIMERPPK'
 'TMBR36A' 'TMBR37' 'TSB' 'WCA2F1' 'WCA2F2' 'WCA2F4' 'WFACNL1' 'WPB-31.2'
 'WPB-33.5' 'WPB-35.4' 'WPB-37.2' 'WPB-38.0' '1RUR' 'BISC50B' 'BISCA8B'
 'BOMATCOUT' 'C51W0.1TS' 'C51W0.6TN' 'C51W1.8N11' 'C51W1.8TN1'
 'C51W1.8TN2' 'C51W1.8TN3' 'C51W1.8TN5' 'C51W1.8TN6' 'C51W1.8TN7'
 'C51W4.4TN1' 'C51W5.8TN1' 'C51W6.7TN1' 'C51W6.7TN2' 'C51W6.7TN3'
 'C51W8.2TN' 'C51W8.3TN' 'CAUC44E' 'CAUC44W' 'CAULK-IN' 'CAUSG3' 'CAUSG5'
 'CR846OK1' 'CUR' 'ENR012' 'EVANS-IN' 'G300' 'G301' 'G302' 'G310' 'G311'
 'G328' 'G329B' 'G330D' 'G332' 'G334' 'G335' 'G342A' 'G342B' 'G342C'
 'G342D' 'G342H' 'G342J' 'G342N' 'G344A' 'G344B' 'G344C' 'G344D' 'G344E'
 'G344F' 'G344G' 'G344H' 'G344I' 'G344J' 'G344K' 'G349C' 'G352B' 'G352C'
 'G353B' 'G353C' 'G354C' 'G367B' 'G367E' 'G368' 'G370' 'G372' 'G374E'
 'G375E' 'G376B' 'G376E' 'G379B' 'G379D' 'G380B' 'G380E' 'G381B' 'G381E'
 'G384B' 'G384E' 'G393B' 'G396B' 'G402A' 'G406' 'G410' 'G434' 'G435'
 'G436' 'G438D' 'G438I' 'G441' 'G507' 'G508' 'G730' 'G734' 'G737' 'G737-D'
 'G782' 'GL03' 'LC03.0TN01' 'ROTA4' 'ROTC1' 'ROTC4' 'S20F' 'S20G' 'S319'
 'S328-D' 'S361' 'S362' 'S371C' 'S382' 'S383' 'S384' 'S486' 'S487' 'S6'
 'SPUR-IN' 'SPUR-OUT' 'TMBR49' 'WC01.11TN' 'WC01.7TW' 'M01C59' 'M01L63N'
 'M01L63S' 'BOMATCIN' 'C44SC4' 'C51W1.8N10' 'C51W1.8TN4' 'C51W1.8TN8'
 'C51W1.8TN9' 'C51W4.4TN2' 'C51W6.7TN4' 'CAU-1RES' 'CAUSG1' 'CAUSG2'
 'CAUSG4' 'CAUSG4PER' 'CAUSG6' 'CAUSG7' 'DF18.3TN' 'G248B' 'G253G' 'G255'
 'G331D' 'G333C' 'L83.8TW1' 'LC0.06TN' 'LC01.7TN' 'LOXA101' 'LOXA104'
 'LOXA104.5' 'LOXA105' 'LOXA107' 'LOXA107U' 'LOXA124' 'LOXA130' 'LOXA135'
 'LOXA136' 'LOXA137' 'LOXA138' 'LOXA139' 'LOXA140' 'LOXAZ0' 'LOXAZ1'
 'LOXAZ2' 'LOXAZ3' 'LOXAZ4' 'MARYS1.4TN' 'ROTA2' 'ROTA3' 'ROTC2' 'ROTC3'
 'ROTE1' 'S175' 'S21A' 'S370C' 'S373A' 'S374A' 'S382CULV' 'SPUR-RES' 'X1'
 'X4' 'C111W1' 'M01C38S' 'C111AC' 'C111JB' 'C111MC' 'C111TC' 'C111N1'
 'C111N2' 'C111USC1' 'C111W3' 'CR92BR1DS' 'TMBR37DS' 'UTS-10' 'UTS-2'
 'UTS-4' 'UTS-6' 'UTS-8' 'UTS-CN' 'UTS-CS' 'UTS-CW' 'UTS-S2' 'L12C1'
 'L10C1' 'L10C2']
Unique parameters: 5
['SECCHI DISK DEPTH' 'TURBIDITY' 'TOTAL SUSPENDED SOLIDS' 'SALINITY'
 'CHLOROPHYLL-A(LC)']

In [69]:
col_to_keep = [
    'station', 'project', 'parameter', 'value',
    'units', 'latitude', 'longitude', 'qualityCode',
    'remarkCode', 'depth','depthUnits', 'uncertainty',
    'collectMethod', 'weatherCode'
]
wq_clean = wq_data[col_to_keep].copy()
wq_clean.head() # clean dataset of raw data and relevant columns

,station,project,parameter,value,units,latitude,longitude,qualityCode,remarkCode,depth,depthUnits,uncertainty,collectMethod,weatherCode
collectDate,,,,,,,,,,,,,,
2018-06-13 09:55:00,JUDGES_DCH,TOHONRP,SECCHI DISK DEPTH,0.0,meters,28.287708,81.383380,A,S,0.0,NaN,NaN,G,0
2018-07-06 09:15:00,JUDGES_DCH,TOHONRP,SECCHI DISK DEPTH,0.0,meters,28.287708,81.383380,A,S,0.0,NaN,NaN,G,0
2018-09-07 10:00:00,JUDGES_DCH,TOHONRP,SECCHI DISK DEPTH,0.0,meters,28.287708,81.383380,A,S,NaN,NaN,NaN,G,0
2018-06-22 12:40:00,LWL-1,LWL,SECCHI DISK DEPTH,0.0,meters,26.843600,80.057508,A,S,0.0,NaN,NaN,G,0
2018-08-23 13:00:00,LWL-1,LWL,SECCHI DISK DEPTH,0.0,meters,26.843600,80.057508,A,S,0.0,NaN,NaN,G,0

In [70]:
print(wq_clean.shape)
print(wq_clean.isnull().sum()) # NaN values in each column

(173696, 14)
station              0
project              0
parameter            0
value                0
units                0
latitude             0
longitude            0
qualityCode          0
remarkCode       91387
depth            25415
depthUnits       24958
uncertainty      36724
collectMethod        0
weatherCode          0
dtype: int64

In [71]:
print(f"Stations with coordinates: {wq_clean['latitude'].notna().sum()}")
print(f"Stations missing coordinates: {wq_clean['latitude'].isna().sum()}")

Stations with coordinates: 173696
Stations missing coordinates: 0

In [72]:
wq_filter = wq_clean.pivot_table(
    index=["collectDate", "station", "latitude", "longitude"],
    columns="parameter",
    values="value",
    aggfunc="mean"
).reset_index()
wq_filter.head() #pivot table with parameters as columns

parameter,collectDate,station,latitude,longitude,CHLOROPHYLL-A(LC),SALINITY,SECCHI DISK DEPTH,TOTAL SUSPENDED SOLIDS,TURBIDITY
0,2015-01-05 07:14:00,S133,27.206467,80.801019,NaN,NaN,NaN,4.0,2.9
1,2015-01-05 07:33:00,S191,27.191991,80.762556,NaN,NaN,NaN,3.0,1.3
2,2015-01-05 07:40:00,S127,27.122578,80.895983,NaN,NaN,NaN,3.0,1.6
3,2015-01-05 07:46:00,S127,27.122578,80.895983,NaN,NaN,NaN,3.0,0.1
4,2015-01-05 07:59:00,S135,27.086633,80.661156,NaN,NaN,NaN,3.0,1.7

In [73]:
# including units in the pivot table causes issues,
# temporariily solved by including lookup table for units
units_lookup = wq_clean.groupby("parameter")["units"].agg(
    lambda x: x.value_counts().index[0]  
).reset_index()
units_lookup.columns = ["parameter", "units"]
units_lookup

                parameter   units
0       CHLOROPHYLL-A(LC)    ug/L
1                SALINITY     PSU
2       SECCHI DISK DEPTH  meters
3  TOTAL SUSPENDED SOLIDS    mg/L
4               TURBIDITY     NTU

In [74]:
print(wq_filter.columns.tolist())
print(wq_filter.head(10))
print(wq_filter.shape)

['collectDate', 'station', 'latitude', 'longitude', 'CHLOROPHYLL-A(LC)', 'SALINITY', 'SECCHI DISK DEPTH', 'TOTAL SUSPENDED SOLIDS', 'TURBIDITY']
parameter         collectDate station   latitude  longitude  \
0         2015-01-05 07:14:00    S133  27.206467  80.801019
1         2015-01-05 07:33:00    S191  27.191991  80.762556
2         2015-01-05 07:40:00    S127  27.122578  80.895983
3         2015-01-05 07:46:00    S127  27.122578  80.895983
4         2015-01-05 07:59:00    S135  27.086633  80.661156
5         2015-01-05 08:06:00    S129  27.030053  81.001451
6         2015-01-05 08:07:00    G310  26.598695  80.445994
7         2015-01-05 08:19:00  C41H78  26.997645  81.068306
8         2015-01-05 08:20:00   S308C  26.984892  80.621428
9         2015-01-05 08:27:00  ENR012  26.597938  80.442350

parameter  CHLOROPHYLL-A(LC)  SALINITY  SECCHI DISK DEPTH  \
0                        NaN       NaN                NaN
1                        NaN       NaN                NaN
2                        NaN       NaN                NaN
3                        NaN       NaN                NaN
4                        NaN       NaN                NaN
5                        NaN       NaN                NaN
6                        NaN       NaN                NaN
7                        NaN       NaN                NaN
8                       2.44       NaN                NaN
9                        NaN       NaN                NaN

parameter  TOTAL SUSPENDED SOLIDS  TURBIDITY
0                             4.0        2.9
1                             3.0        1.3
2                             3.0        1.6
3                             3.0        0.1
4                             3.0        1.7
5                             3.0        2.0
6                             3.0        NaN
7                             3.0        2.4
8                            12.0       23.7
9                             3.0        NaN
(84295, 9)

In [75]:
wq_filter["collectDate"] = pd.to_datetime(wq_filter["collectDate"])

wq_filter["date"] = wq_filter["collectDate"].dt.date

wq_daily = wq_filter.groupby(
    ["date", "station", "latitude", "longitude"]
)[[
    "CHLOROPHYLL-A(LC)",
    "SALINITY",
    "SECCHI DISK DEPTH",
    "TOTAL SUSPENDED SOLIDS",
    "TURBIDITY"
]].mean().reset_index()

wq_daily = wq_daily.rename(columns={
    "date": "Date",
    "station": "Station",
    "latitude": "Latitude",
    "longitude": "Longitude",
    "CHLOROPHYLL-A(LC)": "Chlorophyll-a",
    "SALINITY": "Salinity",
    "SECCHI DISK DEPTH": "Secchi Depth",
    "TOTAL SUSPENDED SOLIDS": "TSS",
    "TURBIDITY": "Turbidity"
})

print(f"Before aggregation: {wq_filter.shape[0]} rows")
print(f"After aggregation: {wq_daily.shape[0]} rows")
wq_daily.head()

Before aggregation: 84295 rows
After aggregation: 61901 rows

parameter,Date,Station,Latitude,Longitude,Chlorophyll-a,Salinity,Secchi Depth,TSS,Turbidity
0,2015-01-05,C38W,27.210483,80.936914,NaN,NaN,NaN,3.0,3.1
1,2015-01-05,C41H78,26.997645,81.068306,NaN,NaN,NaN,3.0,2.4
2,2015-01-05,CULV10A,26.917072,80.613078,NaN,NaN,NaN,8.0,23.8
3,2015-01-05,CULV5,26.919502,81.121732,NaN,NaN,NaN,3.0,3.0
4,2015-01-05,CULV5A,26.885059,81.122010,NaN,NaN,NaN,3.0,1.4

In [76]:
duplicates = wq_daily[wq_daily.duplicated(
    subset=["Date", "Station"], keep=False
)]

print(f"Rows with duplicate station/date combinations: {duplicates.shape[0]}")

Rows with duplicate station/date combinations: 0

In [77]:
wq_daily.columns.name = None
wq_daily = wq_daily.set_index(["Date"])
wq_daily.head()
# Date is index with each parameter displaying as a column

,Station,Latitude,Longitude,Chlorophyll-a,Salinity,Secchi Depth,TSS,Turbidity
Date,,,,,,,,
2015-01-05,C38W,27.210483,80.936914,NaN,NaN,NaN,3.0,3.1
2015-01-05,C41H78,26.997645,81.068306,NaN,NaN,NaN,3.0,2.4
2015-01-05,CULV10A,26.917072,80.613078,NaN,NaN,NaN,8.0,23.8
2015-01-05,CULV5,26.919502,81.121732,NaN,NaN,NaN,3.0,3.0
2015-01-05,CULV5A,26.885059,81.122010,NaN,NaN,NaN,3.0,1.4

In [79]:
print(wq_daily.shape) # still needs to be filtered to just our study area

(61901, 8)